name: Build
on: workflow_dispatch
jobs:
  Windows:
    permissions:
      contents: write
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: google/googletest
          ref: v1.13.0
          path: googletest
      - name: Init MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build googletest
        run: |
          cd googletest
          mkdir build
          cd build
          cmake ../ -Dgtest_force_shared_crt=ON
          cmake --build . --config Debug
          cmake --install . --config Debug --prefix install/Debug
          cmake --build . --config Release
          cmake --install . --config Release --prefix install/Release
      - name: Generate zip
        run: |
          echo ${{ github.sha }} > Release.txt
          Compress-Archive -Path ./googletest/build/install/*,./Release.txt -DestinationPath googletest.win.${{ github.ref_name }}.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: googletest.win.${{ github.ref_name }}.zip
  Linux:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: google/googletest
          ref: v1.13.0
          path: googletest
      - name: Install deps
        run: |
          sudo apt-get -y install gcc-10 g++-10
      - name: Build
        run: |
          alias gcc='gcc-10'
          alias g++='g++-10'
          export CC=`which gcc-10`
          export CXX=`which g++-10`
          cd googletest
          mkdir build
          cd build
          cmake .. -B Release -DCMAKE_BUILD_TYPE=Release -Dgtest_force_shared_crt=ON
          cmake --build Release
          cmake --install Release --prefix install/Release
      - name: Generate tar
        run: |
          echo ${{ github.sha }} > Release.txt
          cp Release.txt ./googletest/build/install/Release
          tar -czvf googletest.linux.${{ github.ref_name }}.tar.gz -C ./googletest/build/install/Release .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: googletest.linux.${{ github.ref_name }}.tar.gz
  macOS:
    permissions:
      contents: write
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: google/googletest
          ref: v1.13.0
          path: googletest
      - name: Build
        run: |
          cd googletest
          mkdir build
          cd build
          cmake .. -B Release -DCMAKE_BUILD_TYPE=Release -Dgtest_force_shared_crt=ON
          cmake --build Release
          cmake --install Release --prefix install/Release
      - name: Generate tar
        run: |
          echo ${{ github.sha }} > Release.txt
          cp Release.txt ./googletest/build/install/Release
          tar -czvf googletest.mac.${{ github.ref_name }}.tar.gz -C ./googletest/build/install/Release .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: googletest.mac.${{ github.ref_name }}.tar.gz